# This is an example Subtitle-Downloader's config file.
locale = '' # en/zh-Hant; default: system locale

[subtitles]
default-language = 'all' # all/en/zh-Hant/zh-Hans/zh-HK/ja/ko
default-format = '.srt'  # .srt/.ass/.vtt
archive = true           # true/false
fix-subtitle = true      # true/false

# Default cookies dir: Subtitle-Downloader/cookies
#         downloads dir: Subtitle-Downloader/downloads
[directories]
cookies = ''
downloads = ''

# Copy user-agent from login browser (https://www.whatsmyua.info/)
[headers]
User-Agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'

[credentials]

[credentials.TMDB]
api_key = '305cd2702459761c82756596508900d7'

[credentials.AppleTVPlus]
cookies = 'tv.apple.com_cookies.txt'

[credentials.CatchPlay]
cookies = 'www.catchplay.com_cookies.txt'

[credentials.Crunchyroll]
cookies = 'www.crunchyroll.com_cookies.txt'

[credentials.DisneyPlus]
email = ''
password = ''

[credentials.FridayVideo]
cookies = 'video.friday.tw_cookies.txt'

[credentials.HBOGOAsia]
email = ''
password = ''

[credentials.iQIYI]
cookies = 'www.iq.com_cookies.txt'

[credentials.meWATCH]
profile_token = ''

[credentials.MyVideo]
cookies = 'www.myvideo.net.tw_cookies.txt'

[credentials.NowE]
cookies = 'www.nowe.com_cookies.txt'

[credentials.NowPlayer]
cookies = 'nowplayer.now.com_cookies.txt'

[credentials.Viki]
cookies = 'www.viki.com_cookies.txt'

[credentials.WeTV]
cookies = 'wetv.vip_cookies.txt'

[credentials.YouTube]
cookies = 'www.youtube.com_cookies.txt'

[proxies]
# This is a dictionary of proxies you wish to use on services that require a specific country IP.
# The dictionary key needs to be an alpha 2 country code (2-letter code, e.g. `us`, `gb`, `jp`, `de`).
# The value needs to be the proxy string which should be recognizable by python-requests and curl.
# e.g.: https://username:password123@subdomain.hostname.ext:89
# If you don't want any, just have this section blank or remove the [proxies] entirely
# us = 'http://127.0.0.1:7890' # Clash

[nordvpn]
# Like `proxies` above, this does the same thing except it automatically generates a proxy string
# for a nordvpn server automatically.
# The credentials should be `Service credentials` NOT your Nord account details!
# https://my.nordaccount.com/dashboard/nordvpn/ (Under advanced configuration).
# ex: https://support.nordvpn.com/Connectivity/Proxy/1087802472/Proxy-setup-on-qBittorrent.htm
username = ''
password = ''
